<?php
require_once __DIR__ . '/includes/config.php';
require_once __DIR__ . '/includes/db.php';
require_once __DIR__ . '/includes/functions.php';

// Ensure FPDF library exists
$fpdfPath = BASE_PATH . '/lib/fpdf/fpdf.php';
if (!file_exists($fpdfPath)) {
    exit('FPDF library not found. Please install it in /lib/fpdf/');
}
require_once $fpdfPath;

$token = trim($_GET['token'] ?? '');

if (!$token || strlen($token) !== 64) {
    http_response_code(400);
    exit('Invalid certificate link.');
}

try {
    $db = get_db();
    $stmt = $db->prepare('SELECT * FROM students WHERE qr_token = ? AND completed_at IS NOT NULL');
    $stmt->execute([$token]);
    $student = $stmt->fetch();

    if (!$student) {
        http_response_code(403);
        exit('Certificate is not yet available for this participant or the link is invalid.');
    }

    $fullName = $student['first_name'] . ' ' . ($student['middle_name'] ? $student['middle_name'][0] . '. ' : '') . $student['last_name'];
    $completionDate = date('F j, Y', strtotime($student['completed_at']));

    // --- PDF Generation using FPDF ---

    class PDF extends FPDF {
        private $certificateId = '';
        private $footerFont = 'Arial'; // Default font

        function __construct($orientation='L', $unit='mm', $size='A4', $certId = '') {
            parent::__construct($orientation, $unit, $size);
            $this->certificateId = $certId;
        }

        function setFooterFont(string $fontFamily): void {
            $this->footerFont = $fontFamily;
        }

        // Page footer
        function Footer() {
            $this->SetY(-15);
            $this->SetFont($this->footerFont,'I',8);
            $this->SetTextColor(150);
            $this->Cell(0,10,'UBBC Bestination 2026 - Certificate ID: ' . $this->certificateId, 0, 0, 'C');
        }
    }

    // A4 paper, landscape orientation
    $pdf = new PDF('L', 'mm', 'A4', substr($token, 0, 16));

    // --- Font Handling ---
    // Use Poppins if font files exist, otherwise fall back to Arial. This prevents fatal errors.
    $fontFamily = 'Arial';
    $fontDir = BASE_PATH . '/lib/fpdf/font/';
    if (file_exists($fontDir . 'Poppins-Regular.php') &&
        file_exists($fontDir . 'Poppins-Bold.php') &&
        file_exists($fontDir . 'Poppins-Italic.php'))
    {
        // These files must be generated by following Tutorial #7 on the FPDF website.
        $pdf->AddFont('Poppins','','Poppins-Regular.php');
        $pdf->AddFont('Poppins','B','Poppins-Bold.php');
        $pdf->AddFont('Poppins','I','Poppins-Italic.php');
        $fontFamily = 'Poppins';
    }
    $pdf->setFooterFont($fontFamily);

    $pdf->AddPage();
    $pdf->SetTitle('Certificate of Completion - ' . $fullName);
    $pdf->SetAutoPageBreak(false);

    // Border
    $pdf->SetLineWidth(1.5);
    $pdf->SetDrawColor(134, 35, 52); // UB Red
    $pdf->Rect(5, 5, 287, 200); // A4 Landscape is 297x210

    // UB Logo
    $pdf->Image(BASE_PATH . '/assets/img/ub-logo-full.png', 125, 15, 50);

    // Main Title
    $pdf->SetFont($fontFamily, 'B', 28);
    $pdf->SetTextColor(134, 35, 52);
    $pdf->Ln(55);
    $pdf->Cell(0, 10, 'Certificate of Completion', 0, 1, 'C');

    // "This certifies that"
    $pdf->SetFont($fontFamily, '', 16);
    $pdf->SetTextColor(0, 0, 0);
    $pdf->Ln(15);
    $pdf->Cell(0, 10, 'This certificate is awarded to', 0, 1, 'C');

    // Student Name
    $pdf->SetFont($fontFamily, 'B', 36);
    $pdf->SetTextColor(0, 0, 0); // UB Black
    $pdf->Ln(10);
    $pdf->Cell(0, 15, $fullName, 0, 1, 'C');

    // "for successfully visiting..."
    $pdf->SetFont($fontFamily, '', 16);
    $pdf->SetTextColor(0, 0, 0);
    $pdf->Ln(10);
    $pdf->Cell(0, 10, 'for successfully visiting all college booths during the', 0, 1, 'C');
    $pdf->SetFont($fontFamily, 'B', 18);
    $pdf->Cell(0, 10, EVENT_NAME, 0, 1, 'C');
    $pdf->SetFont($fontFamily, '', 16);
    $pdf->Cell(0, 10, 'held on ' . $completionDate . '.', 0, 1, 'C');

    $pdf->Output('I', 'Bestination2026-Certificate-' . $student['last_name'] . '.pdf');

} catch (Exception $e) {
    error_log('Certificate generation error: ' . $e->getMessage());
    exit('A system error occurred while generating the certificate.');
}